<?php

namespace App\Http\Controllers;

use App\Models\Voucher;
use App\Models\Order;
use App\Models\Commission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InfluencerController extends Controller
{
    /**
     * Get statistics for the authenticated influencer.
     */
    public function stats(Request $request)
    {
        $user = $request->user();
        $influencerId = $user->id;

        $query = Order::whereHas('voucher', function ($q) use ($influencerId) {
            $q->where('influencer_id', $influencerId);
        });

        if ($request->filled('from')) {
            $query->where('created_at', '>=', Carbon::parse($request->from)->startOfDay());
        }
        if ($request->filled('to')) {
            $query->where('created_at', '<=', Carbon::parse($request->to)->endOfDay());
        }

        $orders = $query->get();

        $stats = [
            'total_sales' => $orders->count(),
            'total_revenue' => $orders->sum('total'),
            'commission_breakdown' => [
                'pending' => $user->influencerCommissions()->where('status', 'pending')->sum('amount'),
                'earned' => $user->influencerCommissions()->where('status', 'earned')->sum('amount'),
                'paid' => $user->influencerCommissions()->where('status', 'paid')->sum('amount'),
            ],
            'recent_activity' => $user->influencerCommissions()->latest()->take(5)->with('order:id,slug,total,created_at')->get()
        ];

        // Specific breakdown per voucher
        $breakdown = Voucher::where('influencer_id', $influencerId)
            ->withCount(['orders' => function($query) use ($request) {
                if ($request->filled('from')) $query->where('created_at', '>=', Carbon::parse($request->from)->startOfDay());
                if ($request->filled('to')) $query->where('created_at', '<=', Carbon::parse($request->to)->endOfDay());
            }])
            ->get(['id', 'code', 'discount_type', 'discount_amount', 'usage_count']);

        return response()->json([
            'success' => true,
            'influencer' => [
                'id' => $user->id,
                'name' => $user->name,
                'email' => $user->email,
            ],
            'summary' => $stats,
            'vouchers' => $breakdown,
        ]);
    }

    /**
     * Get orders generated by this influencer.
     */
    public function conversions(Request $request)
    {
        $user = $request->user();
        $influencerId = $user->id;

        $query = Order::whereHas('voucher', function ($q) use ($influencerId) {
            $q->where('influencer_id', $influencerId);
        })->with('voucher:id,code');

        if ($request->filled('from')) {
            $query->where('created_at', '>=', Carbon::parse($request->from)->startOfDay());
        }
        if ($request->filled('to')) {
            $query->where('created_at', '<=', Carbon::parse($request->to)->endOfDay());
        }

        $orders = $query->select('id', 'slug', 'total', 'status', 'payment_status', 'created_at', 'voucher_id')
            ->latest()
            ->paginate(15);

        return response()->json([
            'success' => true,
            'conversions' => $orders,
        ]);
    }
}
